/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type ApprovedTermExtensionCreate = {
    capitalize: boolean;
    fixCase: boolean;
    fixCommonMistakes: boolean;
};

/** @internal */
export namespace ApprovedTermExtensionCreate$ {
    export type Inbound = {
        capitalize: boolean;
        fixCase: boolean;
        fixCommonMistakes: boolean;
    };

    export const inboundSchema: z.ZodType<ApprovedTermExtensionCreate, z.ZodTypeDef, Inbound> = z
        .object({
            capitalize: z.boolean(),
            fixCase: z.boolean(),
            fixCommonMistakes: z.boolean(),
        })
        .transform((v) => {
            return {
                capitalize: v.capitalize,
                fixCase: v.fixCase,
                fixCommonMistakes: v.fixCommonMistakes,
            };
        });

    export type Outbound = {
        capitalize: boolean;
        fixCase: boolean;
        fixCommonMistakes: boolean;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApprovedTermExtensionCreate> = z
        .object({
            capitalize: z.boolean(),
            fixCase: z.boolean(),
            fixCommonMistakes: z.boolean(),
        })
        .transform((v) => {
            return {
                capitalize: v.capitalize,
                fixCase: v.fixCase,
                fixCommonMistakes: v.fixCommonMistakes,
            };
        });
}
