/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { BriefDocument, BriefDocument$ } from "./briefdocument";
import { Pagination, Pagination$ } from "./pagination";
import { z } from "zod";

export type BriefDocuments = {
    pagination: Pagination;
    result?: Array<BriefDocument> | undefined;
    totalCount: number;
};

/** @internal */
export namespace BriefDocuments$ {
    export type Inbound = {
        pagination: Pagination$.Inbound;
        result?: Array<BriefDocument$.Inbound> | undefined;
        totalCount: number;
    };

    export const inboundSchema: z.ZodType<BriefDocuments, z.ZodTypeDef, Inbound> = z
        .object({
            pagination: Pagination$.inboundSchema,
            result: z.array(BriefDocument$.inboundSchema).optional(),
            totalCount: z.number().int(),
        })
        .transform((v) => {
            return {
                pagination: v.pagination,
                ...(v.result === undefined ? null : { result: v.result }),
                totalCount: v.totalCount,
            };
        });

    export type Outbound = {
        pagination: Pagination$.Outbound;
        result?: Array<BriefDocument$.Outbound> | undefined;
        totalCount: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BriefDocuments> = z
        .object({
            pagination: Pagination$.outboundSchema,
            result: z.array(BriefDocument$.outboundSchema).optional(),
            totalCount: z.number().int(),
        })
        .transform((v) => {
            return {
                pagination: v.pagination,
                ...(v.result === undefined ? null : { result: v.result }),
                totalCount: v.totalCount,
            };
        });
}
