/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ContentSettings = {
    ageAndFamilyStatus: boolean;
    confidence: boolean;
    contentSafeguards: boolean;
    disability: boolean;
    genderIdentitySensitivity: boolean;
    genderInclusiveNouns: boolean;
    genderInclusivePronouns: boolean;
    grammar: boolean;
    healthyCommunication: boolean;
    passiveVoice: boolean;
    raceEthnicityNationalitySensitivity: boolean;
    sexualOrientationSensitivity: boolean;
    spelling: boolean;
    substanceUseSensitivity: boolean;
    unclearReference: boolean;
    wordiness: boolean;
};

/** @internal */
export namespace ContentSettings$ {
    export type Inbound = {
        ageAndFamilyStatus: boolean;
        confidence: boolean;
        contentSafeguards: boolean;
        disability: boolean;
        genderIdentitySensitivity: boolean;
        genderInclusiveNouns: boolean;
        genderInclusivePronouns: boolean;
        grammar: boolean;
        healthyCommunication: boolean;
        passiveVoice: boolean;
        raceEthnicityNationalitySensitivity: boolean;
        sexualOrientationSensitivity: boolean;
        spelling: boolean;
        substanceUseSensitivity: boolean;
        unclearReference: boolean;
        wordiness: boolean;
    };

    export const inboundSchema: z.ZodType<ContentSettings, z.ZodTypeDef, Inbound> = z
        .object({
            ageAndFamilyStatus: z.boolean(),
            confidence: z.boolean(),
            contentSafeguards: z.boolean(),
            disability: z.boolean(),
            genderIdentitySensitivity: z.boolean(),
            genderInclusiveNouns: z.boolean(),
            genderInclusivePronouns: z.boolean(),
            grammar: z.boolean(),
            healthyCommunication: z.boolean(),
            passiveVoice: z.boolean(),
            raceEthnicityNationalitySensitivity: z.boolean(),
            sexualOrientationSensitivity: z.boolean(),
            spelling: z.boolean(),
            substanceUseSensitivity: z.boolean(),
            unclearReference: z.boolean(),
            wordiness: z.boolean(),
        })
        .transform((v) => {
            return {
                ageAndFamilyStatus: v.ageAndFamilyStatus,
                confidence: v.confidence,
                contentSafeguards: v.contentSafeguards,
                disability: v.disability,
                genderIdentitySensitivity: v.genderIdentitySensitivity,
                genderInclusiveNouns: v.genderInclusiveNouns,
                genderInclusivePronouns: v.genderInclusivePronouns,
                grammar: v.grammar,
                healthyCommunication: v.healthyCommunication,
                passiveVoice: v.passiveVoice,
                raceEthnicityNationalitySensitivity: v.raceEthnicityNationalitySensitivity,
                sexualOrientationSensitivity: v.sexualOrientationSensitivity,
                spelling: v.spelling,
                substanceUseSensitivity: v.substanceUseSensitivity,
                unclearReference: v.unclearReference,
                wordiness: v.wordiness,
            };
        });

    export type Outbound = {
        ageAndFamilyStatus: boolean;
        confidence: boolean;
        contentSafeguards: boolean;
        disability: boolean;
        genderIdentitySensitivity: boolean;
        genderInclusiveNouns: boolean;
        genderInclusivePronouns: boolean;
        grammar: boolean;
        healthyCommunication: boolean;
        passiveVoice: boolean;
        raceEthnicityNationalitySensitivity: boolean;
        sexualOrientationSensitivity: boolean;
        spelling: boolean;
        substanceUseSensitivity: boolean;
        unclearReference: boolean;
        wordiness: boolean;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ContentSettings> = z
        .object({
            ageAndFamilyStatus: z.boolean(),
            confidence: z.boolean(),
            contentSafeguards: z.boolean(),
            disability: z.boolean(),
            genderIdentitySensitivity: z.boolean(),
            genderInclusiveNouns: z.boolean(),
            genderInclusivePronouns: z.boolean(),
            grammar: z.boolean(),
            healthyCommunication: z.boolean(),
            passiveVoice: z.boolean(),
            raceEthnicityNationalitySensitivity: z.boolean(),
            sexualOrientationSensitivity: z.boolean(),
            spelling: z.boolean(),
            substanceUseSensitivity: z.boolean(),
            unclearReference: z.boolean(),
            wordiness: z.boolean(),
        })
        .transform((v) => {
            return {
                ageAndFamilyStatus: v.ageAndFamilyStatus,
                confidence: v.confidence,
                contentSafeguards: v.contentSafeguards,
                disability: v.disability,
                genderIdentitySensitivity: v.genderIdentitySensitivity,
                genderInclusiveNouns: v.genderInclusiveNouns,
                genderInclusivePronouns: v.genderInclusivePronouns,
                grammar: v.grammar,
                healthyCommunication: v.healthyCommunication,
                passiveVoice: v.passiveVoice,
                raceEthnicityNationalitySensitivity: v.raceEthnicityNationalitySensitivity,
                sexualOrientationSensitivity: v.sexualOrientationSensitivity,
                spelling: v.spelling,
                substanceUseSensitivity: v.substanceUseSensitivity,
                unclearReference: v.unclearReference,
                wordiness: v.wordiness,
            };
        });
}
