/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GenerationModelInfoResponse } from "./generationmodelinforesponse";
import { Expose, Type } from "class-transformer";

export class GenerationModelsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: GenerationModelInfoResponse })
  @Expose({ name: "data" })
  @Type(() => GenerationModelInfoResponse)
  data?: GenerationModelInfoResponse[];
}
