/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type LinkedTermCreate = {
    linkedTermId?: number | undefined;
    reference?: string | undefined;
};

/** @internal */
export namespace LinkedTermCreate$ {
    export type Inbound = {
        linkedTermId?: number | undefined;
        reference?: string | undefined;
    };

    export const inboundSchema: z.ZodType<LinkedTermCreate, z.ZodTypeDef, Inbound> = z
        .object({
            linkedTermId: z.number().int().optional(),
            reference: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.linkedTermId === undefined ? null : { linkedTermId: v.linkedTermId }),
                ...(v.reference === undefined ? null : { reference: v.reference }),
            };
        });

    export type Outbound = {
        linkedTermId?: number | undefined;
        reference?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LinkedTermCreate> = z
        .object({
            linkedTermId: z.number().int().optional(),
            reference: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.linkedTermId === undefined ? null : { linkedTermId: v.linkedTermId }),
                ...(v.reference === undefined ? null : { reference: v.reference }),
            };
        });
}
