/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type SectionInfo = {
    id: number;
    title: string;
    url: string;
};

/** @internal */
export namespace SectionInfo$ {
    export type Inbound = {
        id: number;
        title: string;
        url: string;
    };

    export const inboundSchema: z.ZodType<SectionInfo, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int(),
            title: z.string(),
            url: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                title: v.title,
                url: v.url,
            };
        });

    export type Outbound = {
        id: number;
        title: string;
        url: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SectionInfo> = z
        .object({
            id: z.number().int(),
            title: z.string(),
            url: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                title: v.title,
                url: v.url,
            };
        });
}
