/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type TermTagCreate = {
    tag: string;
};

/** @internal */
export namespace TermTagCreate$ {
    export type Inbound = {
        tag: string;
    };

    export const inboundSchema: z.ZodType<TermTagCreate, z.ZodTypeDef, Inbound> = z
        .object({
            tag: z.string(),
        })
        .transform((v) => {
            return {
                tag: v.tag,
            };
        });

    export type Outbound = {
        tag: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TermTagCreate> = z
        .object({
            tag: z.string(),
        })
        .transform((v) => {
            return {
                tag: v.tag,
            };
        });
}
