/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TermUpdate } from "./termupdate";
import { Expose, Type } from "class-transformer";

export enum UpdateTermsRequestFailHandling {
  Accumulate = "accumulate",
  Validate = "validate",
  Skip = "skip",
  ValidateOnly = "validateOnly",
}

export class UpdateTermsRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "failHandling" })
  failHandling?: UpdateTermsRequestFailHandling;

  @SpeakeasyMetadata({ elemType: TermUpdate })
  @Expose({ name: "models" })
  @Type(() => TermUpdate)
  models?: TermUpdate[];
}
