/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { classToPlain, Expose } from "class-transformer";

export class FailMessage extends Error {
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "extras" })
    extras: any;

    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key: string;

    constructor(err?: FailMessage) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "FailMessage";
        Object.setPrototypeOf(this, FailMessage.prototype);
    }
}
