/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type AddTermsRequest = {
    createTermsRequest: shared.CreateTermsRequest;
    teamId: number;
    organizationId?: number | undefined;
};

export type AddTermsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    createTermsResponse?: shared.CreateTermsResponse | undefined;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace AddTermsRequest$ {
    export type Inbound = {
        CreateTermsRequest: shared.CreateTermsRequest$.Inbound;
        teamId: number;
        organizationId?: number | undefined;
    };

    export const inboundSchema: z.ZodType<AddTermsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            CreateTermsRequest: shared.CreateTermsRequest$.inboundSchema,
            teamId: z.number().int(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                createTermsRequest: v.CreateTermsRequest,
                teamId: v.teamId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });

    export type Outbound = {
        CreateTermsRequest: shared.CreateTermsRequest$.Outbound;
        teamId: number;
        organizationId?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddTermsRequest> = z
        .object({
            createTermsRequest: shared.CreateTermsRequest$.outboundSchema,
            teamId: z.number().int(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                CreateTermsRequest: v.createTermsRequest,
                teamId: v.teamId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });
}

/** @internal */
export namespace AddTermsResponse$ {
    export type Inbound = {
        ContentType: string;
        CreateTermsResponse?: shared.CreateTermsResponse$.Inbound | undefined;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<AddTermsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            CreateTermsResponse: shared.CreateTermsResponse$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.CreateTermsResponse === undefined
                    ? null
                    : { createTermsResponse: v.CreateTermsResponse }),
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        CreateTermsResponse?: shared.CreateTermsResponse$.Outbound | undefined;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddTermsResponse> = z
        .object({
            contentType: z.string(),
            createTermsResponse: shared.CreateTermsResponse$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.createTermsResponse === undefined
                    ? null
                    : { CreateTermsResponse: v.createTermsResponse }),
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
