/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import * as z from "zod";

export type CreateCompletionRequest = {
    completionRequest: shared.CompletionRequest;
    modelId: string;
    organizationId?: number | undefined;
};

export type CreateCompletionResponse = {
    completionResponse?: shared.CompletionResponse | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreateCompletionRequest$ {
    export type Inbound = {
        CompletionRequest: shared.CompletionRequest$.Inbound;
        modelId: string;
        organizationId?: number | undefined;
    };

    export const inboundSchema: z.ZodType<CreateCompletionRequest, z.ZodTypeDef, Inbound> = z
        .object({
            CompletionRequest: shared.CompletionRequest$.inboundSchema,
            modelId: z.string(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                completionRequest: v.CompletionRequest,
                modelId: v.modelId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });

    export type Outbound = {
        CompletionRequest: shared.CompletionRequest$.Outbound;
        modelId: string;
        organizationId?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateCompletionRequest> = z
        .object({
            completionRequest: shared.CompletionRequest$.outboundSchema,
            modelId: z.string(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                CompletionRequest: v.completionRequest,
                modelId: v.modelId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });
}

/** @internal */
export namespace CreateCompletionResponse$ {
    export type Inbound = {
        CompletionResponse?: shared.CompletionResponse$.Inbound | undefined;
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<CreateCompletionResponse, z.ZodTypeDef, Inbound> = z
        .object({
            CompletionResponse: shared.CompletionResponse$.inboundSchema.optional(),
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.CompletionResponse === undefined
                    ? null
                    : { completionResponse: v.CompletionResponse }),
                contentType: v.ContentType,
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        CompletionResponse?: shared.CompletionResponse$.Outbound | undefined;
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateCompletionResponse> = z
        .object({
            completionResponse: shared.CompletionResponse$.outboundSchema.optional(),
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.completionResponse === undefined
                    ? null
                    : { CompletionResponse: v.completionResponse }),
                ContentType: v.contentType,
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
