/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export enum SortField {
    Shortcut = "shortcut",
    CreationTime = "creationTime",
    ModificationTime = "modificationTime",
}

export enum SortOrder {
    Asc = "asc",
    Desc = "desc",
}

export type FindSnippetsRequest = {
    limit?: number | undefined;
    offset?: number | undefined;
    organizationId?: number | undefined;
    search?: string | undefined;
    shortcuts?: Array<string> | undefined;
    sortField?: SortField | undefined;
    sortOrder?: SortOrder | undefined;
    tags?: Array<string> | undefined;
    teamId: number;
};

export type FindSnippetsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    paginatedResultSnippetWithUser?: shared.PaginatedResultSnippetWithUser | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const SortField$ = z.nativeEnum(SortField);

/** @internal */
export const SortOrder$ = z.nativeEnum(SortOrder);

/** @internal */
export namespace FindSnippetsRequest$ {
    export type Inbound = {
        limit?: number | undefined;
        offset?: number | undefined;
        organizationId?: number | undefined;
        search?: string | undefined;
        shortcuts?: Array<string> | undefined;
        sortField?: SortField | undefined;
        sortOrder?: SortOrder | undefined;
        tags?: Array<string> | undefined;
        teamId: number;
    };

    export const inboundSchema: z.ZodType<FindSnippetsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            limit: z.number().int().optional(),
            offset: z.number().int().optional(),
            organizationId: z.number().int().optional(),
            search: z.string().optional(),
            shortcuts: z.array(z.string()).optional(),
            sortField: SortField$.optional(),
            sortOrder: SortOrder$.optional(),
            tags: z.array(z.string()).optional(),
            teamId: z.number().int(),
        })
        .transform((v) => {
            return {
                ...(v.limit === undefined ? null : { limit: v.limit }),
                ...(v.offset === undefined ? null : { offset: v.offset }),
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
                ...(v.search === undefined ? null : { search: v.search }),
                ...(v.shortcuts === undefined ? null : { shortcuts: v.shortcuts }),
                ...(v.sortField === undefined ? null : { sortField: v.sortField }),
                ...(v.sortOrder === undefined ? null : { sortOrder: v.sortOrder }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
                teamId: v.teamId,
            };
        });

    export type Outbound = {
        limit?: number | undefined;
        offset?: number | undefined;
        organizationId?: number | undefined;
        search?: string | undefined;
        shortcuts?: Array<string> | undefined;
        sortField?: SortField | undefined;
        sortOrder?: SortOrder | undefined;
        tags?: Array<string> | undefined;
        teamId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FindSnippetsRequest> = z
        .object({
            limit: z.number().int().optional(),
            offset: z.number().int().optional(),
            organizationId: z.number().int().optional(),
            search: z.string().optional(),
            shortcuts: z.array(z.string()).optional(),
            sortField: SortField$.optional(),
            sortOrder: SortOrder$.optional(),
            tags: z.array(z.string()).optional(),
            teamId: z.number().int(),
        })
        .transform((v) => {
            return {
                ...(v.limit === undefined ? null : { limit: v.limit }),
                ...(v.offset === undefined ? null : { offset: v.offset }),
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
                ...(v.search === undefined ? null : { search: v.search }),
                ...(v.shortcuts === undefined ? null : { shortcuts: v.shortcuts }),
                ...(v.sortField === undefined ? null : { sortField: v.sortField }),
                ...(v.sortOrder === undefined ? null : { sortOrder: v.sortOrder }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
                teamId: v.teamId,
            };
        });
}

/** @internal */
export namespace FindSnippetsResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        PaginatedResult_SnippetWithUser?:
            | shared.PaginatedResultSnippetWithUser$.Inbound
            | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<FindSnippetsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            PaginatedResult_SnippetWithUser:
                shared.PaginatedResultSnippetWithUser$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                ...(v.PaginatedResult_SnippetWithUser === undefined
                    ? null
                    : { paginatedResultSnippetWithUser: v.PaginatedResult_SnippetWithUser }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        PaginatedResult_SnippetWithUser?:
            | shared.PaginatedResultSnippetWithUser$.Outbound
            | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FindSnippetsResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            paginatedResultSnippetWithUser:
                shared.PaginatedResultSnippetWithUser$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                ...(v.paginatedResultSnippetWithUser === undefined
                    ? null
                    : { PaginatedResult_SnippetWithUser: v.paginatedResultSnippetWithUser }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
