/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type GetDocumentDetailsRequest = {
    documentId: number;
    teamId: number;
    organizationId?: number | undefined;
};

export type GetDocumentDetailsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    document?: shared.Document | undefined;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetDocumentDetailsRequest$ {
    export type Inbound = {
        documentId: number;
        teamId: number;
        organizationId?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetDocumentDetailsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            documentId: z.number().int(),
            teamId: z.number().int(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                documentId: v.documentId,
                teamId: v.teamId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });

    export type Outbound = {
        documentId: number;
        teamId: number;
        organizationId?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDocumentDetailsRequest> = z
        .object({
            documentId: z.number().int(),
            teamId: z.number().int(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                documentId: v.documentId,
                teamId: v.teamId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });
}

/** @internal */
export namespace GetDocumentDetailsResponse$ {
    export type Inbound = {
        ContentType: string;
        Document?: shared.Document$.Inbound | undefined;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetDocumentDetailsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Document: shared.Document$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Document === undefined ? null : { document: v.Document }),
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Document?: shared.Document$.Outbound | undefined;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDocumentDetailsResponse> = z
        .object({
            contentType: z.string(),
            document: shared.Document$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.document === undefined ? null : { Document: v.document }),
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
