/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import * as z from "zod";

export type GetFileRequest = {
    fileId: string;
    organizationId?: number | undefined;
};

export type GetFileResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    modelFile?: shared.ModelFile | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetFileRequest$ {
    export type Inbound = {
        fileId: string;
        organizationId?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetFileRequest, z.ZodTypeDef, Inbound> = z
        .object({
            fileId: z.string(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                fileId: v.fileId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });

    export type Outbound = {
        fileId: string;
        organizationId?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetFileRequest> = z
        .object({
            fileId: z.string(),
            organizationId: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                fileId: v.fileId,
                ...(v.organizationId === undefined ? null : { organizationId: v.organizationId }),
            };
        });
}

/** @internal */
export namespace GetFileResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        ModelFile?: shared.ModelFile$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetFileResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            ModelFile: shared.ModelFile$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                ...(v.ModelFile === undefined ? null : { modelFile: v.ModelFile }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        ModelFile?: shared.ModelFile$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetFileResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            modelFile: shared.ModelFile$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                ...(v.modelFile === undefined ? null : { ModelFile: v.modelFile }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
