/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import * as z from "zod";

export enum ListUsersQueryParamSortField {
    Id = "id",
    Name = "name",
    CreationTime = "creationTime",
    Deleted = "deleted",
    ModificationTime = "modificationTime",
    Email = "email",
    LastSeen = "lastSeen",
}

export enum ListUsersQueryParamSortOrder {
    Asc = "asc",
    Desc = "desc",
}

export type ListUsersRequest = {
    limit?: number | undefined;
    offset?: number | undefined;
    search?: string | undefined;
    sortField?: ListUsersQueryParamSortField | undefined;
    sortOrder?: ListUsersQueryParamSortOrder | undefined;
};

export type ListUsersResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    paginatedResultUserPublicResponse?: shared.PaginatedResultUserPublicResponse | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const ListUsersQueryParamSortField$ = z.nativeEnum(ListUsersQueryParamSortField);

/** @internal */
export const ListUsersQueryParamSortOrder$ = z.nativeEnum(ListUsersQueryParamSortOrder);

/** @internal */
export namespace ListUsersRequest$ {
    export type Inbound = {
        limit?: number | undefined;
        offset?: number | undefined;
        search?: string | undefined;
        sortField?: ListUsersQueryParamSortField | undefined;
        sortOrder?: ListUsersQueryParamSortOrder | undefined;
    };

    export const inboundSchema: z.ZodType<ListUsersRequest, z.ZodTypeDef, Inbound> = z
        .object({
            limit: z.number().int().optional(),
            offset: z.number().int().optional(),
            search: z.string().optional(),
            sortField: ListUsersQueryParamSortField$.optional(),
            sortOrder: ListUsersQueryParamSortOrder$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.limit === undefined ? null : { limit: v.limit }),
                ...(v.offset === undefined ? null : { offset: v.offset }),
                ...(v.search === undefined ? null : { search: v.search }),
                ...(v.sortField === undefined ? null : { sortField: v.sortField }),
                ...(v.sortOrder === undefined ? null : { sortOrder: v.sortOrder }),
            };
        });

    export type Outbound = {
        limit?: number | undefined;
        offset?: number | undefined;
        search?: string | undefined;
        sortField?: ListUsersQueryParamSortField | undefined;
        sortOrder?: ListUsersQueryParamSortOrder | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListUsersRequest> = z
        .object({
            limit: z.number().int().optional(),
            offset: z.number().int().optional(),
            search: z.string().optional(),
            sortField: ListUsersQueryParamSortField$.optional(),
            sortOrder: ListUsersQueryParamSortOrder$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.limit === undefined ? null : { limit: v.limit }),
                ...(v.offset === undefined ? null : { offset: v.offset }),
                ...(v.search === undefined ? null : { search: v.search }),
                ...(v.sortField === undefined ? null : { sortField: v.sortField }),
                ...(v.sortOrder === undefined ? null : { sortOrder: v.sortOrder }),
            };
        });
}

/** @internal */
export namespace ListUsersResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        PaginatedResult_UserPublicResponse?:
            | shared.PaginatedResultUserPublicResponse$.Inbound
            | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<ListUsersResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            PaginatedResult_UserPublicResponse:
                shared.PaginatedResultUserPublicResponse$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                ...(v.PaginatedResult_UserPublicResponse === undefined
                    ? null
                    : { paginatedResultUserPublicResponse: v.PaginatedResult_UserPublicResponse }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        PaginatedResult_UserPublicResponse?:
            | shared.PaginatedResultUserPublicResponse$.Outbound
            | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListUsersResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            paginatedResultUserPublicResponse:
                shared.PaginatedResultUserPublicResponse$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                ...(v.paginatedResultUserPublicResponse === undefined
                    ? null
                    : { PaginatedResult_UserPublicResponse: v.paginatedResultUserPublicResponse }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
