/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../sdk/models/errors";
import * as operations from "../sdk/models/operations";

export class Content extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }
    /**
     * Check your content against your preset styleguide.
     */
    async check(
        input: operations.ContentCheckRequest,
        options?: RequestOptions
    ): Promise<operations.ContentCheckResponse> {
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Content-Type", "application/json");
        headers.set("Accept", "application/json");

        const payload = operations.ContentCheckRequest$.outboundSchema.parse(input);

        const body = enc$.encodeJSON("body", payload.ContentRequest, { explode: true });

        const pathParams = {
            organizationId: enc$.encodeSimple(
                "organizationId",
                payload.organizationId ?? this.options$.organizationId,
                { explode: false, charEncoding: "percent" }
            ),
            teamId: enc$.encodeSimple("teamId", payload.teamId, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path = this.templateURLComponent(
            "/content/organization/{organizationId}/team/{teamId}/check"
        )(pathParams);

        const security = this.options$.apiKey ? { apiKey: this.options$.apiKey } : {};
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "post", path, headers, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.ContentCheckResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                ProcessedContent: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, [400, 401, 403, 404, 500], "application/json")) {
            const responseBody = await response.json();
            const result = errors.FailResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                ...responseBody,
            });
            throw new errors.FailResponse(result);
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Apply the style guide suggestions directly to your content.
     */
    async correct(
        input: operations.ContentCorrectRequest,
        options?: RequestOptions
    ): Promise<operations.ContentCorrectResponse> {
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Content-Type", "application/json");
        headers.set("Accept", "application/json");

        const payload = operations.ContentCorrectRequest$.outboundSchema.parse(input);

        const body = enc$.encodeJSON("body", payload.ContentRequest, { explode: true });

        const pathParams = {
            organizationId: enc$.encodeSimple(
                "organizationId",
                payload.organizationId ?? this.options$.organizationId,
                { explode: false, charEncoding: "percent" }
            ),
            teamId: enc$.encodeSimple("teamId", payload.teamId, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path = this.templateURLComponent(
            "/content/organization/{organizationId}/team/{teamId}/correct"
        )(pathParams);

        headers.set(
            "X-Request-ID",
            enc$.encodeSimple("X-Request-ID", payload["X-Request-ID"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const security = this.options$.apiKey ? { apiKey: this.options$.apiKey } : {};
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "post", path, headers, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.ContentCorrectResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                CorrectionResponse: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, [400, 401, 403, 404, 500], "application/json")) {
            const responseBody = await response.json();
            const result = errors.FailResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                ...responseBody,
            });
            throw new errors.FailResponse(result);
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }
}
