/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../sdk/models/errors";
import * as operations from "../sdk/models/operations";

export class Snippet extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }
    /**
     * Delete snippets
     */
    async delete(
        input: operations.DeleteSnippetsRequest,
        options?: RequestOptions
    ): Promise<operations.DeleteSnippetsResponse> {
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Accept", "application/json");

        const payload = operations.DeleteSnippetsRequest$.outboundSchema.parse(input);
        const body = null;

        const pathParams = {
            organizationId: enc$.encodeSimple(
                "organizationId",
                payload.organizationId ?? this.options$.organizationId,
                { explode: false, charEncoding: "percent" }
            ),
            teamId: enc$.encodeSimple("teamId", payload.teamId, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path = this.templateURLComponent(
            "/snippet/organization/{organizationId}/team/{teamId}"
        )(pathParams);

        const query = [
            enc$.encodeForm("ids", payload.ids, { explode: true, charEncoding: "percent" }),
        ]
            .filter(Boolean)
            .join("&");

        headers.set(
            "X-Request-ID",
            enc$.encodeSimple("X-Request-ID", payload["X-Request-ID"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const security = this.options$.apiKey ? { apiKey: this.options$.apiKey } : {};
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "delete", path, headers, query, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.DeleteSnippetsResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                DeleteResponse: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, [400, 401, 403, 404, 500], "application/json")) {
            const responseBody = await response.json();
            const result = errors.FailResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                ...responseBody,
            });
            throw new errors.FailResponse(result);
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Find snippets
     */
    async find(
        input: operations.FindSnippetsRequest,
        options?: RequestOptions
    ): Promise<operations.FindSnippetsResponse> {
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Accept", "application/json");

        const payload = operations.FindSnippetsRequest$.outboundSchema.parse(input);
        const body = null;

        const pathParams = {
            organizationId: enc$.encodeSimple(
                "organizationId",
                payload.organizationId ?? this.options$.organizationId,
                { explode: false, charEncoding: "percent" }
            ),
            teamId: enc$.encodeSimple("teamId", payload.teamId, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path = this.templateURLComponent(
            "/snippet/organization/{organizationId}/team/{teamId}"
        )(pathParams);

        const query = [
            enc$.encodeForm("limit", payload.limit, { explode: true, charEncoding: "percent" }),
            enc$.encodeForm("offset", payload.offset, { explode: true, charEncoding: "percent" }),
            enc$.encodeForm("search", payload.search, { explode: true, charEncoding: "percent" }),
            enc$.encodeForm("shortcuts", payload.shortcuts, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("sortField", payload.sortField, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("sortOrder", payload.sortOrder, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("tags", payload.tags, { explode: true, charEncoding: "percent" }),
        ]
            .filter(Boolean)
            .join("&");

        const security = this.options$.apiKey ? { apiKey: this.options$.apiKey } : {};
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "get", path, headers, query, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.FindSnippetsResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                PaginatedResult_SnippetWithUser: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, [400, 401, 403, 404, 500], "application/json")) {
            const responseBody = await response.json();
            const result = errors.FailResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                ...responseBody,
            });
            throw new errors.FailResponse(result);
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Update snippets
     */
    async update(
        input: operations.UpdateSnippetsRequest,
        options?: RequestOptions
    ): Promise<operations.UpdateSnippetsResponse> {
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Content-Type", "application/json");
        headers.set("Accept", "application/json");

        const payload = operations.UpdateSnippetsRequest$.outboundSchema.parse(input);

        const body = enc$.encodeJSON("body", payload.RequestBody, { explode: true });

        const pathParams = {
            organizationId: enc$.encodeSimple(
                "organizationId",
                payload.organizationId ?? this.options$.organizationId,
                { explode: false, charEncoding: "percent" }
            ),
            teamId: enc$.encodeSimple("teamId", payload.teamId, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path = this.templateURLComponent(
            "/snippet/organization/{organizationId}/team/{teamId}"
        )(pathParams);

        headers.set(
            "X-Request-ID",
            enc$.encodeSimple("X-Request-ID", payload["X-Request-ID"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const security = this.options$.apiKey ? { apiKey: this.options$.apiKey } : {};
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "put", path, headers, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.UpdateSnippetsResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                classes: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, [400, 401, 403, 404, 500], "application/json")) {
            const responseBody = await response.json();
            const result = errors.FailResponse$.inboundSchema.parse({
                ...responseFields,
                Headers: this.unpackHeaders(response.headers),
                ...responseBody,
            });
            throw new errors.FailResponse(result);
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }
}
